### ISSUE TITLE
feature request: Quarter

### ISSUE THREAD

**Issue by tallums** [jacwright/date.format#11]
Jacob,

Will you add this to date.format.js for Quarter? If this code is not correct, please let me know what's wrong with it.

// Quarter
Q: function() { var d = new Date(); return Math.floor((d.getMonth() + 3) / 3); },

Thanks!
Tim Allums

**Comment by jacwright** [comment]
This code is getting the quarter of a new date object which will represent NOW. It needs to use `this.getMonth()` to get the quarter of the current date object.
