### ISSUE TITLE
dateformat does't work on latest firefox.

### ISSUE THREAD

**Issue by MHL3060** [jacwright/date.format#4]
for example. I am currently in EDT.

the utc timestamp = 1394355600000
d = new Date(utc) gives me 
Date 2014-03-09T09:00:00.000Z

d.format('T') gives EST which is wrong.

d.format('T') should give EDT.

**Comment by kevit-development** [comment]
@MHL3060 does the issue still persist in the latest Firefox version, also, what version have u tried it in?

**Comment by MHL3060** [comment]
Sorry. I haven't tried. We don't support Firefox anymore.

**Comment by kevit-development** [comment]
I have tried it in Firefox 54.0.1, seems to work fine after the [ceb72c6](https://github.com/jacwright/date.format/commit/ceb72c6126be80a5a9b33b95c39747d114fa2bdb) commit.
